server:
  compression:
    enabled: true
  # Default port
  port: 8080
  # Enable graceful shutdown - Server will wait for active request to finish
  shutdown: graceful
  tomcat:
    mbeanregistry:
      enabled: true
spring:
  application:
    name: elastic-search
  # Time to wait for active requests to finish during the shutdown
  lifecycle:
    timeout-per-shutdown-phase: 20s
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none

spring.security.oauth2.client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:${server.port}/login/oauth2/code/google
          scope:
            - openid
            - profile
            - email
#          authorization-grant-type: authorization_code

# Swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
logging:
  level:
    ua:
      huryn:
        elasticsearch: ${LOGGING_LEVEL:INFO}

startup:
  add-data: ${ADD_DATA:false}
google:
  api-key: ${API_KEY}
app:
  local-directory: local-resource
  cuisine-types: Українська,Американська,Італійська,Французька,Німецька,Азійська,Грецька,Мексиканська,Веганська

